name: Pipeline CI/CD Atividade Avaliativa

on:
  push:
    branches: [ FIXME ]
  pull_request:
    branches: [ FIXME ]

jobs:
  build_e_testes:
    name: Job de Integracao Continua (CI)
    runs-on: FIXME

    steps:
      - name: Checkout do Repositorio
        uses: actions/checkout@v4

      - name: Executar Testes Simulados
        run: |
          echo "Executando testes automatizados do app.py..."
          # FIXME: Insira abaixo o comando para executar ou testar o arquivo app.py
          FIXME

  deploy_qa:
    name: Job de Entrega Continua (CD - Homologacao)
    runs-on: ubuntu-latest
    needs: [ FIXME ]

    steps:
      - name: Deploy em Ambiente de QA
        run: |
          echo "Deploy realizado no Ambiente de Homologacao/QA!"
